export default {
  MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
  MARK_NOTIFICATION_AS_UNREAD_BY_ID: 'MARK_NOTIFICATION_AS_UNREAD_BY_ID',
  MARK_ALL_NOTIFICATIONS_AS_READ: 'MARK_ALL_NOTIFICATIONS_AS_READ',
  START_UPDATING_NOTICIFATION_STATE: 'START_UPDATING_NOTICIFATION_STATE',
  FINISH_UPDATING_NOTIFICATION_STATE: 'FINISH_UPDATING_NOTIFICATION_STATE',
  RECEVIED_NOTIFICATIONS: 'RECEVIED_NOTIFICATIONS',
  FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',

  START_LOGIN: 'START_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  CHANGE_AVATAR: 'CHANGE_AVATAR'
} 

